version: '3'
services:
  authorization_module:
    build:
      context: ./authorization_module
    depends_on:
      - db
    ports:
      - 80:80
      - 9229:9229
    volumes:
      - ./app:/usr/src/app

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080

volumes:
  db_data:
